name: kisan_ai
description: AI-Powered Crop & Soil Management (offline-first demo)
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  riverpod: ^2.5.1
  image_picker: ^1.0.7
  tflite_flutter: ^0.10.4
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/tflite/disease_model.tflite
    - assets/tflite/labels.txt
    - assets/data/crop_coefficients.json
    - assets/data/rotation_rules.json
